Public Class Form1
    'Rob Churches
    'Multiplication quiz game
    Private Sub resetter()
        'Procedure to reset all variables and clear objects on form to start again
        Controls.Clear()
        InitializeComponent()
        username = ""
        usernum1 = 0
        usernum2 = 0
        userguesses = 0
    End Sub
    Private Sub getuserguesses()
        'Procedure to get user input and calculate the user product
        'increment guesses by 1
        usernum1 = CInt(InputBox(username & ", What is the first factor?"))
        usernum2 = CInt(InputBox(username & ", What is your second factor?"))
        userproduct = usernum1 * usernum2 ' MsgBox(usernum1 & " " & usernum2 & " = " & userproduct)
        userguesses += 1
    End Sub
    Private Sub Start()
        'Procedure to run the main program
        'Check to see if user has typed in a name yet and if not get them to type in a name
        'Show a welcome message to the user
        If username = "" Then
            username = InputBox("What is your name?")
            txtResult.Text = "Howdy " & username & " !!" & vbCrLf & "Let's see how good you are at your Times Table"
        End If
        'generate 2 random numbers that represent the 2 factors 
        Randomize()
        num1 = 9 ' Int(Rnd() * 12) + 1
        num2 = 4 'Int(Rnd() * 12) + 1
        'MsgBox(num1 & " " & num2)
        product = num1 * num2
        getuserguesses()

        While num1 <> usernum1 Or num2 <> usernum2 'Loop until user types the two factors generated by AI

            If userproduct = product Then
                'if the product of the user numbers entered as the AI
                'Show appropriate msg in text box and get user to rpeat the process
                txtResult.Text += vbCrLf & "Rob, The answer below is correct but the question is incorrect"
                txtResult.Text += vbCrLf & usernum1 & " x " & usernum2
                getuserguesses()
            Else
                If userproduct > product Then
                    'if the product of the user numbers entered is larger than the  AI product
                    'Show appropriate msg in text box and get user to repeat process
                    txtResult.Text += vbCrLf & "The answer is lower than "
                    txtResult.Text += vbCrLf & usernum1 & " x " & usernum2
                    getuserguesses()
                Else
                    'if the product of the user numbers entered is less than the  AI product
                    'Show appropriate msg in text box and get user to repeat process
                    txtResult.Text += vbCrLf & "The answer is higher than "
                    txtResult.Text += vbCrLf & usernum1 & " x " & usernum2
                    getuserguesses()
                End If
            End If
        End While
        'Feedback to user they got the correct answer and question and the total guesses
        txtResult.Text += vbCrLf & username & ", The question and answer is correct. Number of guesses = " & userguesses

    End Sub

    Private Sub btnExit_Click(sender As Object, e As EventArgs) Handles btnExit.Click
        'End App
        Application.Exit()
    End Sub

    Private Sub btnReset_Click(sender As Object, e As EventArgs) Handles btnReset.Click
        resetter()
    End Sub
    Private Sub btnStart_Click(sender As Object, e As EventArgs) Handles btnStart.Click
        Start()
    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        resetter()
        'Get user name and give msg in text box
        username = InputBox("What is your name?")
        txtResult.Text = "Howdy " & username & " !!" & vbCrLf & "Let's see how good you are at your Times Table"
    End Sub

End Class
